import = [
    "~/.config/alacritty/themes/themes/coolnight.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"
opacity = 0.85
blur = true
option_as_alt = "Both"

[font]
normal.family = "Operator Mono Lig"

#regular
size = 14

#for video
# size = 35.0
